github.com:
    users:
        Hiansdt:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Hiansdt
