github.com:
    users:
        Hiansdt:
            oauth_token: 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
    git_protocol: https
    user: Hiansdt
    oauth_token: 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
